FROM hashicorp/terraform:1.7

ARG UID=1000
ARG GID=1000

RUN addgroup -g $GID appgroup
RUN adduser -D -u $UID -G appgroup appuser

# Update and install dependencies
RUN apk --no-cache update && \
    apk --no-cache upgrade && \
    apk add --no-cache make && \
    # Add any specific packages you need to install here, e.g., apk add --no-cache git
    rm -rf /var/cache/apk/*

WORKDIR /module

COPY ./hashicorp/terraform/azure/bootstrap .

ENTRYPOINT [ "sh", "./entrypoint.sh" ]


